services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

  odoo:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8068:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - ODOO_EXTRA_ADDONS=account,sale,your_module
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./enterprise:/mnt/enterprise
      - ./addons:/mnt/extra-addons
    command: odoo --dev=xml -d dealership --db_host=db --db_user=odoo --db_password=odoo --db_port=5432
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ayanfiscoss@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

volumes:
  odoo-web-data:
  odoo-db-data:
